// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.serjann.force.domain;

import com.serjann.force.domain.MechDataOnDemand;
import java.lang.String;
import java.util.Calendar;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MechIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MechIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MechIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MechIntegrationTest: @Transactional;
    
    @Autowired
    private MechDataOnDemand MechIntegrationTest.dod;
    
    @Test
    public void MechIntegrationTest.testCountMeches() {
        Assert.assertNotNull("Data on demand for 'Mech' failed to initialize correctly", dod.getRandomMech());
        long count = Mech.countMeches();
        Assert.assertTrue("Counter for 'Mech' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MechIntegrationTest.testFindMech() {
        Mech obj = dod.getRandomMech();
        Assert.assertNotNull("Data on demand for 'Mech' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mech' failed to provide an identifier", id);
        obj = Mech.findMech(id);
        Assert.assertNotNull("Find method for 'Mech' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Mech' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MechIntegrationTest.testFindAllMeches() {
        Assert.assertNotNull("Data on demand for 'Mech' failed to initialize correctly", dod.getRandomMech());
        long count = Mech.countMeches();
        Assert.assertTrue("Too expensive to perform a find all test for 'Mech', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Mech> result = Mech.findAllMeches();
        Assert.assertNotNull("Find all method for 'Mech' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Mech' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MechIntegrationTest.testFindMechEntries() {
        Assert.assertNotNull("Data on demand for 'Mech' failed to initialize correctly", dod.getRandomMech());
        long count = Mech.countMeches();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Mech> result = Mech.findMechEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Mech' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Mech' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MechIntegrationTest.testFlush() {
        Mech obj = dod.getRandomMech();
        Assert.assertNotNull("Data on demand for 'Mech' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mech' failed to provide an identifier", id);
        obj = Mech.findMech(id);
        Assert.assertNotNull("Find method for 'Mech' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMech(obj);
        Calendar currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Mech' failed to increment on flush directive", (currentVersion != null && obj.getVersion().after(currentVersion)) || !modified);
    }
    
    @Test
    public void MechIntegrationTest.testMergeUpdate() {
        Mech obj = dod.getRandomMech();
        Assert.assertNotNull("Data on demand for 'Mech' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mech' failed to provide an identifier", id);
        obj = Mech.findMech(id);
        boolean modified =  dod.modifyMech(obj);
        Calendar currentVersion = obj.getVersion();
        Mech merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Mech' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion().after(currentVersion)) || !modified);
    }
    
    @Test
    public void MechIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Mech' failed to initialize correctly", dod.getRandomMech());
        Mech obj = dod.getNewTransientMech(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Mech' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Mech' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Mech' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MechIntegrationTest.testRemove() {
        Mech obj = dod.getRandomMech();
        Assert.assertNotNull("Data on demand for 'Mech' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mech' failed to provide an identifier", id);
        obj = Mech.findMech(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Mech' with identifier '" + id + "'", Mech.findMech(id));
    }
    
}
